version: "1.0"

http:
  host: "0.0.0.0"
  port: 8080
  readTimeout: 5s
  writeTimeout: 5s
  idleTimeout: 60s

postgres:
  host: "localhost"
  port: 5432
  user: "app"
  password: "secret"
  dbname: "ai_photo"
  maxOpenConns: 20
  maxIdleConns: 10
  connMaxLifetime: 30m

seaweedfs:
  baseURL: "http://localhost:8888"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  dialTimeout: 2s
  readTimeout: 1s
  writeTimeout: 1s
  poolSize: 10

clip:
  host: "localhost"
  port: 8003
  
faiss:
  host: "faiss-service"
  port: 19530

log:
  level: "debug" # "info", "debug", "warn", "error"
  format: "json" # "json", "text"
  sourceFolder: "AI_photo_retrieval_system/backend"
