version: "1.0.0"

http:
  host: "0.0.0.0"
  port: 8080
  readTimeout: 5s
  writeTimeout: 5s
  idleTimeout: 30s

postgres:
  host: "localhost"  # hostname -I
  port: 5433
  user: "postgres"
  password: "postgres"
  dbname: "media"
  sslmode: "disable"
  maxOpenConns: 10
  maxIdleConns: 5
  connMaxLifetime: 1h
  connMaxIdleTime: 600s
  healthCheckPeriod: 300s

redis:
  addr: "localhost:6380"
  password: ""
  db: 0
  dialTimeout: 5s
  readTimeout: 5s
  writeTimeout: 5s
  poolSize: 10

seaweedfs:
  baseURL: "http://localhost:8888"

clip:
  host: "localhost"
  port: 8005

faiss:
  host: "localhost"
  port: 8006
  
log:
  level: "debug" 
  format: "text"
  sourceFolder: "backend"
