version: "1.0.0"

http:
  host: "0.0.0.0"
  port: 8080
  readTimeout: "10s"
  writeTimeout: "10s"
  idleTimeout: "60s"

postgres:
  host: media_postgres
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "media"
  maxOpenConns: 25
  maxIdleConns: 5
  connMaxLifetime: "5m"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  dialTimeout: 2s
  readTimeout: 1s
  writeTimeout: 1s
  poolSize: 10

seaweedfs:
  baseURL: "http://localhost:8888"

clip:
  host: "clip-service"
  port: 8001

faiss:
  host: "faiss-service"
  port: 8002

log:
  level: "debug" # "info", "debug", "warn", "error"
  format: "json" # "json", "text"
  sourceFolder: "backend"
