name: ai-photo-retrieval

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-api
    command: ["./photo-backend", "--config=/config/docker.yaml"]
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - seaweedfs
      - ml_service
      - vector_service
    environment:
      - CONFIG_PATH=/config/docker.yaml
    volumes:
      - ./backend/config:/config
    networks:
      - clip-net

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    container_name: backend-worker
    command: ["./photo-worker", "--config=/config/docker.yaml"]
    depends_on:
      - redis
      - postgres
      - seaweedfs
      - ml_service
      - vector_service
    networks:
      - clip-net
    environment:
      - CONFIG_PATH=/config/docker.yaml
    volumes:
      - ./backend/config:/config





  postgres:
    image: postgres:15
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=media
    volumes:
      - ./volumes/pg:/var/lib/postgresql/data
    networks: [clip-net]
  
  seaweedfs:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs
    command: "server -dir=/data -volume.max=10 -filer -s3"
    ports:
      - "9333:9333"   # master 
      - "8888:8888"   # filer (HTTP file API) 
      - "8333:8333"   # S3 gateway 
      - "18080:18080" # volume UI 
    volumes:
      - ./seaweed-data:/data
    networks: [clip-net]

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks: [clip-net]


  ml_service:
    build: ./ml_service
    container_name: ml-service
    expose: ["8003"]
    ports: ["8005:8003"]
    networks: [clip-net]

  vector_service:
    build: ./vector_service
    container_name: vector-service
    expose: ["8002"]
    ports: ["8006:8002"]
    depends_on:
      milvus:
        condition: service_healthy
    networks: [clip-net]

  etcd:  # metadata storage for milvus
    image: quay.io/coreos/etcd:v3.5.5
    container_name: milvus-etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./volumes/etcd:/etcd
    networks: [clip-net]

  minio:  # minimal input output service for milvus (object storage)
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: milvus-minio
    command: minio server /minio_data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ./volumes/minio:/minio_data
    networks: [clip-net]

  milvus:
    image: milvusdb/milvus:v2.3.0
    container_name: milvus-standalone
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ./volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
    depends_on:
      - "etcd"
      - "minio"
    networks: [clip-net]


networks:
  clip-net:
    name: clip-net

volumes:
  redis-data: