# ---- Build stage ----
    FROM golang:1.24.5-alpine AS builder
    WORKDIR /app
    
    # Copy Go modules
    COPY go.mod go.sum ./
    RUN go mod download
    
    # Copy project files
    COPY . .
    
    # Build static binary (no CGO)
    ENV CGO_ENABLED=0
    RUN go build -ldflags="-s -w" -o photo-worker ./cmd/worker
    
    # ---- Runtime stage ----
    FROM alpine:3.19
    WORKDIR /app
    
    # Minimal dependencies
    RUN apk add --no-cache ca-certificates tzdata bash tini
    
    # Copy binary and config
    COPY --from=builder /app/photo-worker .
    COPY config/docker.yaml ./config.yaml
    
    
    ENTRYPOINT ["/sbin/tini", "--"]
    CMD ["./photo-worker", "--config=config.yaml"]
    